<?php

/**
 * @file
 * Contains mailchimp_signup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function mailchimp_signup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the mailchimp_signup module.
    case 'help.page.mailchimp_signup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Simple Mailchimp signup that delegates early to Mailchimp and focuses on display options.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function mailchimp_signup_theme() {
  return [
    'closable_button' => [
      'variables' => [
        'mailing_list_description' => '',
        'button_label' => '',
        'signup_form_url' => '',
        'button_link' => [],
      ],
      'render element' => 'children',
    ],
  ];
}
